"""empty message

Revision ID: 26c4dc1f7fb3
Revises: f15843956663
Create Date: 2018-09-25 16:12:25.202869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c4dc1f7fb3'
down_revision = 'f15843956663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=2000), nullable=True),
    sa.Column('purchase_list', sa.String(length=500), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_vendor_latitude_longitude', table_name='vendor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vendor_latitude_longitude', 'vendor', ['latitude_longitude'], unique=False)
    op.drop_table('rating')
    # ### end Alembic commands ###
