"""empty message

Revision ID: aac1431cd759
Revises: f624a004145c
Create Date: 2018-09-18 11:30:05.770740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac1431cd759'
down_revision = 'f624a004145c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
