"""empty message

Revision ID: b53d29933bfa
Revises: 
Create Date: 2018-08-17 15:25:54.613590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b53d29933bfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    measurementunit = postgresql.ENUM('pound', 'basket', 'crop', name='measurementunit')
    measurementunit.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('location', sa.String(length=400), nullable=False))
    op.add_column('listing', sa.Column('measurement_unit', sa.Enum('pound', 'basket', 'crop', name='measurementunit'), nullable=False))
    op.add_column('listing', sa.Column('price_per_unit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'price_per_unit')
    op.drop_column('listing', 'measurement_unit')
    op.drop_column('listing', 'location')   
    # ### end Alembic commands ###

    measurementunit = postgresql.ENUM('pound', 'basket', 'crop', name='measurementunit')
    measurementunit.drop(op.get_bind())
