"""empty message

Revision ID: cb0221d80614
Revises: 26c4dc1f7fb3
Create Date: 2018-09-26 11:26:50.474106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0221d80614'
down_revision = '26c4dc1f7fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'vendor_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('vendor_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
