"""empty message

Revision ID: f15843956663
Revises: aac1431cd759
Create Date: 2018-09-19 14:20:35.399485

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2.types


# revision identifiers, used by Alembic.
revision = 'f15843956663'
down_revision = 'aac1431cd759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vendor_type', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('latitude_longitude', geoalchemy2.types.Geography(geometry_type='POINT'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    # ### end Alembic commands ###
